### ISSUE TITLE
Can not install the most recent version

### ISSUE THREAD

**Issue by y1my1** [JuliaPy/Seaborn.jl#19]
the version installed in my Mac when trying `] add Seaborn` is v0.4.1,  then I tried to install it from GitHub but not succeed

```
(@v1.4) pkg> add Seaborn#master
   Updating git-repo `https://github.com/JuliaPy/Seaborn.jl.git`
ERROR: could not find project file in package at https://github.com/JuliaPy/Seaborn.jl.git
```

can you please tell me where maybe the problem? Thanks

**Comment by jotwin** [comment]
I also have this problem. It would be useful to have a functional scatterplot.

**Comment by JoelTrent** [comment]
This issue is the same as #21 - for some reason updating to v0.4.5 is restricted and v0.4.1 is the highest @jotwin, @JackRab and I can update to of Seaborn.jl. Removing the package and reinstalling results in v0.4.1 being installed; updating it from there results in a restriction and subsequent failure. I've checked the package requirements in 'REQUIRE' and I have more recent versions of all of these. Apologies, I'm not quite sure why this is!

For those looking for a workaround (like me) that don't know how to get v0.4.5, but do want to use `lineplot()` etc. - copy the code in Seaborn.jl from v0.4.5 and paste that into the Seaborn.jl that is on your hard drive (on Mac this was in a hidden folder tree which contained all of Julia's files and packages).

Then you'll need to save that file, stop and start Julia and re-precompile Seaborn; `using Seaborn` should do the trick.

This successfully worked for me yesterday

**Comment by malmaud** [comment]
I'll look into it

**Comment by malmaud** [comment]
I updated the project to add a Project.toml file, which should fix this. Just waiting for new version to be registered (https://github.com/JuliaRegistries/General/pull/43156) now.

**Comment by malmaud** [comment]
Fixed by https://github.com/JuliaPy/Seaborn.jl/pull/24

**Comment by JoelTrent** [comment]
Thanks @malmaud! Re-updated the package last week and it worked perfectly

**Comment by malmaud** [comment]
Great!
